[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'Worker - pulando build phase'"]

[start]
cmd = "node worker.standalone.js"