[variables]
NODE_ENV = "production"
REDIS_URL = ""
SKIP_ENV_VALIDATION = "1"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"