[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs_20', 'npm', 'chromium']

[phases.install]
cmds = ['npm ci --ignore-scripts', 'npx prisma generate']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'